### PR TITLE
fixes #59

### LINKED ISSUE #59: No \tmp dir on windows, seeds.go can't download products and slideshow images
```
open file ("http://qor3.s3.amazonaws.com/01-tee-c.20160316044516567824937.png") failure, got err open \tmp\01-tee-c.20160316044516567824937.png: The system cannot find the path specified.
open file ("banner") failure, got err open \tmp\google_banner.jpg: The system cannot find the path specified.
open file ("qor_logo") failure, got err open \tmp\qor_logo.png: The system cannot find the path specified.
open file ("banner") failure, got err open \tmp\slide1.jpg: The system cannot find the path specified.
```

if I change method `openFileByURL` in `db\seeds\main.go` to:
```
filepath.Join("", fileName)
```
it will pollute qor-example folder (from wich I've run `go run db/seeds/main.go db/seeds/seeds.go`), but put all of downloaded images inside `public/system` folder and example works fine

When I'am trying to use `filepath.Join(os.TempDir(), fileName)`, products works just fine, but slideshow images doesn't, they even doesn't copied in folder `public/system` and url in html is:
```
/system/qor_widget_settings/TopBanner/image/C:%5cUsers%5cMIRONO~1%5cAppData%5cLocal%5cTemp%5cslide1.20170206133517827284700.jpg
```

### PR DESCRIPTION
**Pull request by alexmironof**

### CODE REVIEW

**Comment by jinzhu** [comment]
thank you for your pr.

**Comment by alexmironof** [comment]
@jinzhu I think this was also missclicked :smile:

**Comment by jinzhu** [comment]
I must be drunk ;)

**Comment by alexmironof** [comment]
Oh nice thanks :+1:  It's freelancers dream to work with mug of beer and in only underpants :laughing: :rofl:

**Pull request closed without merging**
